### ISSUE TITLE
Issues executing find_stable.py {ModuleNotFoundError: No module named 'bs4'}

### ISSUE THREAD

**Issue by DeletedUser-0** [Ben-0-mad/YT-TMS-Finder#10]
Hello, I hope you are having a great day (yes, it's me, again), 

I followed all the instructions (ofc), I'm using Windows, but when I type `python find_stable.py`, I still have the following error:

- `Traceback (most recent call last):
  File "find_stable.py", line 6, in <module>
    import bs4 as bs                        #for working with html source file
ModuleNotFoundError: No module named 'bs4'`

**Comment by Ben-0-mad** [comment]
Please do ```pip install beautifulsoup4```. I thought this was the requirements.txt but apparently I forgot it.

**Comment by DeletedUser-0** [comment]
oh thanks!
