### ISSUE TITLE
Can't identify songs: "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary"

### ISSUE THREAD

**Issue by DeletedUser-0** [Ben-0-mad/YT-TMS-Finder#11]
Hello, I hope you are having a great day (or you aren't because I am always begging for help, sorry).

When I type the channel url the following error appears: 

`sqlite - connection opened
Traceback (most recent call last):
  File "find_stable.py", line 379, in <module>
    finder.check_channel()
  File "find_stable.py", line 301, in check_channel
    source = self.get_channel_source()
  File "find_stable.py", line 219, in get_channel_source
    driver = webdriver.Chrome()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
sqlite - connection has been closed`

Can you help me?

**Comment by Ben-0-mad** [comment]
I saw someone have trouble with this. "Cannot find chrome binary", this is why I included the step ```choco install chromedriver``` in the setup, because then it's automatically added to the PATH variable. If you did ```choco install chromedriver``` open a new CMD to ensure that it's able to recognise the chromedriver.

**Comment by DeletedUser-0** [comment]
It isn't working, probably because of my antivirus. No, it's not. It isn't actually working.

**Comment by DeletedUser-0** [comment]
If you read this, it isnt working

**Comment by Ben-0-mad** [comment]
Unfortunately I don't know how to fix it, I was really hoping that choco install would help you. But there might be some helpful information for you on this page: https://stackoverflow.com/questions/50138615/webdriverexception-unknown-error-cannot-find-chrome-binary-error-with-selenium

**Comment by Ben-0-mad** [comment]
Okay actually I have an idea:
1. Open file explorer, and go to your C: drive. Search for "chromedriver.exe".
2. Copy the file location of "chromedriver.exe" (there might be multiple, choose one, preferably the one from chocolatey\bin)
3. Open the "find_stable.py" file replace line 188 (this line: ```driver = webdriver.Chrome()```) by 

```driver = webdriver.Chrome(executable_path = r"C:\ProgramData\chocolatey\bin\chromedriver.exe")```
where you use the file location for your chromedriver.exe that you have, probably you can use the same file location as me since we both have choco installed. Please try this, I think this should help you!

**Comment by DeletedUser-0** [comment]
thanks, I will try now!

**Comment by DeletedUser-0** [comment]
Oh I see the problem now!

When I typed "choco install chromedriver.exe" in that folder, this error appeared to me:

`Chocolatey v0.10.15
Installing the following packages:
chromedriver.exe
By installing you accept licenses for the packages.
chromedriver.exe not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify --pre,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - chromedriver.exe - chromedriver.exe not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify --pre,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.`

**Comment by Ben-0-mad** [comment]
Oh yes you should use chromedriver instead of chromedriver.exe in the choco install chromedriver command. Did you manage to get it to work with all this info?

**Comment by DeletedUser-0** [comment]
Yes, I did everything to try to work.

**Comment by Ben-0-mad** [comment]
Nice if it works then I'll close this issue now.

**Comment by DeletedUser-0** [comment]
No, it isn't working

**Comment by Ben-0-mad** [comment]
It should look like this. If you specify the correct path, this will 100% work.
![chromedriver](https://user-images.githubusercontent.com/41330651/95080869-025a9600-0719-11eb-82c5-4a1501f33a26.png)

But then you need to use your own path to the chromedriver.exe
