### ISSUE TITLE
Bot says "All videos have been checked or are longer than than the maximum duration" as soon as I start running it

### ISSUE THREAD

**Issue by ghost** [Ben-0-mad/YT-TMS-Finder#17]
This happens with any channel URL I try. I've updated chromedriver, youtube-dl, ffmpeg and pyaudio, and I've also looked through check_channel() in find_stable.py for any errors.
pls help

**Comment by Ben-0-mad** [comment]
Are you sure this also happens with channels  which you have not checked before?

**Comment by ghost** [comment]
yep, it happens with every single channel url

**Comment by Ben-0-mad** [comment]
I found the problem, Google has updated their website. When selenium tries to open the URL you first land on an agreement page. This makes the code mess up. I found it still works if you quickly click on "AGREE" so we just have to give a user more time to click on that button, which is what I did in commit 605423c.
