### ISSUE TITLE
Bot crashes when trying to search through channels with 'premiere' videos

### ISSUE THREAD

**Issue by ghost** [Ben-0-mad/YT-TMS-Finder#19]
screenshot:
![image](https://user-images.githubusercontent.com/57552959/130093566-aa4e5be7-2b05-47de-979d-9672a0d2ce5f.png)

channel to test: https://www.youtube.com/c/Wherepostrockdwells/about

**Comment by Ben-0-mad** [comment]
This issue should be fixed with 299989da0006bdfe786b66b16137d6676967e084
