### ISSUE TITLE
Bot stops searching big channel after about 100 or so videos

### ISSUE THREAD

**Issue by ghost** [Ben-0-mad/YT-TMS-Finder#20]
I tried searching one fairly large channel about 3 times, and each time the search ends after 300 - 400 seconds on 3 threads and only about 100 or so videos get searched, which is impossible because the channel I'm trying to search has over 1'000 videos.
This is the channel in question if you need to test it: https://www.youtube.com/c/postrockinstrumental/videos

**Comment by Ben-0-mad** [comment]
The reason not all videos get checked is because the bot does not check videos longer than 210 seconds (did this for TMS but of course for other songs you'd have to change the source code) so you can now set the max duration and min duration yourself (see 3960143662c13fbcf1da3c76bd096a5435c7fdb5)
