### ISSUE TITLE
Video audio couldn't be downloaded

### ISSUE THREAD

**Issue by stgogil** [Ben-0-mad/YT-TMS-Finder#21]
Hi!

Loving the code. I'm trying to use it to find songs other than TMMS, however, I keep getting the same error:

`Video audio couldn't be downloaded. Skipping for now. Please check missed.txt for more info.`

When I open `missed.txt`, it says
`2023-10-29 11:00:05: Could not check video with ID e2lyYEUPat8. Please copy and paste this URL in your browser to check: 'youtube.com/watch?v=e2lyYEUPat8'`
for each video.

I am using Ubuntu 22.04. Don't know what could be causing this error.

**Comment by stgogil** [comment]
Solved it by manually updating youtube-dl directly from the official github.

**Comment by Ben-0-mad** [comment]
> Solved it by manually updating youtube-dl directly from the official github.

This is also how I solved it back when I was still using it. I think YouTube updates their site regularly and youtube-dl has to be up to date to actually work. To prevent having to constantly update the yt-dl binary you could use the yt-dl python package and at the start of code execution check for updates to the package but at this point the project is no longer being maintained.
